### ISSUE TITLE
Exception: Interface maps for generic interfaces on arrays cannot be retrieved

### ISSUE THREAD

**Issue by Nufflee** [CosmosOS/IL2CPU#26] opened 2017-11-11 21:51 UTC
Hey guys, I have a really weird issue, I have this code (https://pastebin.com/JQiqN3py) and it's giving me this exception (https://pastebin.com/TQbFKTCW ). I have also tried commenting out the code and it still had the same exception (potentially a problem with the build system?). How can I fix this?

Cheers!

**Comment by jp2masa** [comment] 2017-11-11 22:43
This is a duplicate of #15

**Comment by charlesbetros** [comment] 2017-11-11 23:59
In this case a plug for string split would be better and relatively simple. It worked before net core and we won't have generic interfaces on arrays for a while.

**Comment by charlesbetros** [comment] 2017-11-12 00:03
Moving this to the main cosmos repo and rewording to specifically mention adding a plug.

**Closed by charlesbetros** 2017-11-12 00:03 UTC
Labels: Duplicate

**Comment by jp2masa** [comment] 2017-11-12 00:16
The problem here is using `Skip(int)` on an array,

**Comment by charlesbetros** [comment] 2017-11-12 00:38
Oh. My mistake. :) I thought it was on string.
